import heroBg from "@/imports/image.png";

const goals = [
  "Chung tay bảo vệ môi trường sống, giảm thiểu ô nhiễm và cải thiện cảnh quan đô thị theo hướng xanh – sạch – bền vững.",
  "Nâng cao nhận thức và trách nhiệm của cộng đồng, đặc biệt là thế hệ trẻ, trong việc gìn giữ môi trường và tài nguyên thiên nhiên.",
  "Lan tỏa lối sống xanh, khuyến khích những hành động thiết thực và lâu dài vì sự phát triển bền vững.",
  "Kết nối và phát huy sức mạnh tình nguyện, từng bước hình thành mạng lưới hành động vì môi trường rộng khắp.",
  "Đề cao sáng tạo, đổi mới và những giải pháp bảo vệ môi trường phù hợp với điều kiện thực tiễn.",
  "Hướng tới ứng dụng khoa học – công nghệ trong bảo vệ môi trường, truyền thông và quản lý tổ chức.",
  "Phát triển thành một tổ chức xã hội chuyên nghiệp, uy tín và có sức ảnh hưởng tích cực trong lĩnh vực môi trường.",
];

const campaigns = [
  ["Dọn rác Sông Hồng 2024", "Hơn 1.000 lượt tình nguyện viên, thu gom hàng trăm tấn rác và góp phần khắc phục ô nhiễm sau bão."],
  ["Dọn rác Dương Quang 2024", "Khoảng 200 tình nguyện viên làm sạch khu dân cư và các tuyến mương thoát nước."],
  ["Vì dòng sông không rác 2025", "Khoảng 700 lượt tình nguyện viên cùng giảm rác thải ra sông và nâng cao ý thức bảo vệ nguồn nước."],
  ["Bảo vệ màu xanh chủ quyền 2025", "200 lượt tình nguyện viên kết hợp bảo vệ môi trường với giáo dục tinh thần yêu nước nhân dịp 80 năm Quốc khánh."],
  ["Gom rác góp xanh – Xuân tình nguyện 2025", "8 trường đại học và khoảng 300 lượt tình nguyện viên cùng lan tỏa lối sống xanh trong giới trẻ."],
];

export default function AboutPage() {
  return <>
    <section className="relative overflow-hidden px-4 pb-20 pt-36 text-center text-white"><img src={heroBg} alt="Tình nguyện viên Hà Nội Xanh" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-emerald-950/85" /><div className="relative mx-auto max-w-4xl"><span className="rounded bg-emerald-700 px-3 py-1 text-xs font-bold uppercase">Về Hà Nội Xanh</span><h1 className="mt-5 text-4xl font-black sm:text-6xl">Chung tay vì một Việt Nam xanh – sạch – đẹp</h1><blockquote className="mx-auto mt-6 max-w-3xl text-lg text-emerald-100 sm:text-xl">“Mang tinh thần xung kích của tuổi trẻ, Hà Nội Xanh không ngừng học hỏi, đổi mới, sáng tạo và nuôi dưỡng khát vọng vươn mình để hành động vì môi trường và cộng đồng.”</blockquote></div></section>

    <section className="bg-white py-20"><div className="mx-auto max-w-6xl px-4"><div className="grid items-start gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Hình thành và phát triển</p><h2 className="mt-3 text-3xl font-black">Từ 3 thành viên đến một cộng đồng hành động rộng lớn</h2><div className="mt-6 space-y-4 leading-relaxed text-gray-600"><p>Hà Nội Xanh được thành lập vào tháng 12/2022 với xuất phát điểm chỉ có 3 thành viên. Đến nay, tổ chức đã thu hút hơn 1.000 tình nguyện viên tham gia chính thức và ghi nhận khoảng 20.000 lượt tham gia trong các hoạt động.</p><p>Hà Nội Xanh là tổ chức xã hội quy tụ tình nguyện viên từ nhiều độ tuổi, ngành nghề và địa phương, cùng chung mục tiêu cải thiện ô nhiễm tại Thủ đô và nâng cao trách nhiệm xã hội trong cộng đồng.</p><p>Từ hoạt động thu gom rác, tổ chức đã mở rộng sang truyền thông giáo dục, thiện nguyện, sử dụng tài nguyên bền vững và triển khai những giải pháp dài hạn như hệ thống phao chắn rác.</p></div></div><div className="grid grid-cols-2 gap-4">{[["12/2022", "Thời điểm thành lập"], ["1.000+", "Tình nguyện viên chính thức"], ["20.000", "Lượt tham gia"], ["200+", "Chiến dịch môi trường"], ["50+ km", "Sông, mương được làm sạch"], ["3 năm", "Hoạt động liên tục"]].map(([value, label]) => <div key={label} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><strong className="block text-2xl text-emerald-800 sm:text-3xl">{value}</strong><span className="mt-2 block text-xs font-bold uppercase text-gray-600">{label}</span></div>)}</div></div></div></section>

    <section className="bg-emerald-950 py-20 text-white"><div className="mx-auto max-w-6xl px-4"><div className="mx-auto max-w-3xl text-center"><p className="text-sm font-bold uppercase tracking-widest text-emerald-400">Tôn chỉ và mục tiêu hoạt động</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Hành động đến cùng vì một tương lai bền vững</h2><blockquote className="mt-5 text-emerald-200">“Dám đối diện hiện thực, đổi mới tư duy và hành động đến cùng – đó là cách tuổi trẻ Hà Nội Xanh nuôi dưỡng khát vọng và chung tay kiến tạo một Việt Nam xanh, bền vững.”</blockquote></div><ol className="mt-12 grid gap-4 md:grid-cols-2">{goals.map((goal, index) => <li key={goal} className="flex gap-4 rounded-2xl border border-white/10 bg-white/5 p-5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-emerald-500 font-black text-emerald-950">{index + 1}</span><p className="text-sm leading-relaxed text-emerald-50">{goal}</p></li>)}</ol></div></section>

    <section className="bg-gray-50 py-20"><div className="mx-auto max-w-7xl px-4"><div className="text-center"><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Hoạt động tiêu biểu</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Những chiến dịch tạo dấu ấn</h2><p className="mx-auto mt-4 max-w-3xl text-gray-600">Hoạt động được triển khai từ thực tiễn môi trường, dựa trên tư duy đổi mới và hướng tới giá trị bền vững cho cộng đồng.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{campaigns.map(([title, text]) => <article key={title} className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="text-lg font-black text-emerald-800">{title}</h3><p className="mt-3 text-sm leading-relaxed text-gray-600">{text}</p></article>)}</div><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="rounded-2xl bg-emerald-100 p-6"><h3 className="font-black text-emerald-900">Giáo dục và truyền thông</h3><p className="mt-3 text-sm text-gray-700">Tổ chức tọa đàm, chia sẻ tại các trường đại học nhằm thúc đẩy nhận thức và hành động của sinh viên.</p></article><article className="rounded-2xl bg-orange-100 p-6"><h3 className="font-black text-orange-900">Thiện nguyện cộng đồng</h3><p className="mt-3 text-sm text-gray-700">Hỗ trợ nhu yếu phẩm cho vùng cao, vùng khó khăn và lan tỏa tinh thần tương thân tương ái.</p></article><article className="rounded-2xl bg-blue-100 p-6"><h3 className="font-black text-blue-900">Phao chắn rác</h3><p className="mt-3 text-sm text-gray-700">Lắp đặt hệ thống tại sông Nhuệ và sông Vũ Thư để hạn chế rác trôi, bảo vệ nguồn nước lâu dài.</p></article></div></div></section>

    <section className="bg-white py-20"><div className="mx-auto grid max-w-6xl gap-10 px-4 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Người sáng lập</p><h2 className="mt-3 text-3xl font-black">Nguyễn Tiến Huy</h2><p className="mt-1 text-sm text-gray-500">Sinh ngày 11/10/1995 · Quê quán Hải Phòng</p><p className="mt-6 leading-relaxed text-gray-600">Sau thời gian sinh sống và làm việc tại Hà Nội, anh cùng hai người bạn nhen nhóm ý tưởng thành lập dự án khi chứng kiến rác thải và ô nhiễm tại các kênh, mương và bờ sông của Thủ đô.</p><blockquote className="mt-6 rounded-2xl border-l-4 border-orange-500 bg-orange-50 p-5 font-semibold text-gray-800">“Chúng ta đã được sinh ra trên một mảnh đất màu mỡ. Hãy chung tay bảo vệ môi trường để sau này con cái chúng ta sinh ra không phải sống trên rác thải.”</blockquote></div><div><p className="text-sm font-bold uppercase tracking-widest text-emerald-700">Truyền thông và ghi nhận</p><h2 className="mt-3 text-3xl font-black">Câu chuyện đẹp được lan tỏa</h2><p className="mt-5 text-gray-600">Các chiến dịch của Hà Nội Xanh đã được VTV1, VTV3, VTV4, Báo Lao Động, Đài Tiếng nói Việt Nam, Đài Hà Nội và VTC1 đồng hành đưa tin.</p><ul className="mt-6 space-y-3 text-sm"><li className="rounded-xl bg-gray-50 p-4"><strong>Giải thưởng Tình nguyện Quốc gia 2023</strong><br />Do Trung ương Đoàn TNCS Hồ Chí Minh trao tặng.</li><li className="rounded-xl bg-gray-50 p-4"><strong>Gương điển hình tiên tiến Người tốt, Việc tốt 2023</strong><br />Đại diện tổ chức tham dự chương trình của Ban Thi đua – Khen thưởng Trung ương.</li><li className="rounded-xl bg-gray-50 p-4"><strong>Các chương trình truyền hình</strong><br />Điểm tựa Việt Nam, Việc tử tế – Chuyển động 24h và Chắp cánh trên VTV1.</li></ul></div></div></section>

    <section className="bg-emerald-100 py-16"><div className="mx-auto max-w-5xl px-4 text-center"><h2 className="text-3xl font-black text-emerald-950">Kết nối với Hà Nội Xanh</h2><div className="mt-8 grid gap-4 text-sm md:grid-cols-2 lg:grid-cols-4"><a className="rounded-xl bg-white p-4 font-bold text-emerald-800" href="tel:+84987231832">+84 98 723 18 32</a><a className="rounded-xl bg-white p-4 font-bold text-emerald-800" href="mailto:hanoixanhh@gmail.com">hanoixanhh@gmail.com</a><a className="rounded-xl bg-white p-4 font-bold text-emerald-800" href="https://www.facebook.com/share/1DF83NSNX1/" target="_blank" rel="noreferrer">Facebook Hà Nội Xanh ↗</a><a className="rounded-xl bg-white p-4 font-bold text-emerald-800" href="https://www.tiktok.com/@hanoi_xanh" target="_blank" rel="noreferrer">TikTok @hanoi_xanh ↗</a></div><p className="mt-6 text-sm text-emerald-900">117 Xuân Thủy, phường Cầu Giấy, Hà Nội</p></div></section>
  </>;
}
