import { Link } from "react-router-dom";
import heroBg from "@/imports/image.png";
import mapRefImg from "@/imports/image-2.png";
import { BEFORE_AFTER_ITEMS, CAMPAIGN_EVENTS, CLEANUP_LOCATIONS } from "@/app/data";
import { eventHasEnded, formatVietnameseDate } from "@/app/utils";

const news = [
  ["Hành trình 500 ngày hồi sinh sông Tô Lịch của người trẻ Thủ đô", "25/08/2026", "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=600&auto=format&fit=crop"],
  ["Những chiến sĩ 'lội bùn' giữa lòng thành phố", "22/08/2026", "https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=600&auto=format&fit=crop"],
  ["Bí quyết phân loại và tái chế rác thải nhựa", "18/08/2026", "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=600&auto=format&fit=crop"],
];

function Heading({ eyebrow, title, text, light = false }: { eyebrow: string; title: string; text: string; light?: boolean }) {
  return <div className="mx-auto mb-12 max-w-3xl text-center"><p className={`text-xs font-bold uppercase tracking-widest ${light ? "text-emerald-400" : "text-emerald-700"}`}>{eyebrow}</p><h2 className={`mt-3 text-3xl font-black sm:text-4xl ${light ? "text-white" : "text-gray-900"}`}>{title}</h2><p className={`mt-3 ${light ? "text-emerald-200" : "text-gray-600"}`}>{text}</p></div>;
}

export default function HomePage() {
  const upcoming = CAMPAIGN_EVENTS.filter((event) => !eventHasEnded(event));
  return <>
    <section className="relative flex min-h-[88vh] items-center justify-center overflow-hidden px-4 pb-16 pt-28 text-center text-white"><img src={heroBg} alt="Tình nguyện viên Hà Nội Xanh dọn rác trên sông" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-emerald-950/75 to-black/70" /><div className="relative mx-auto w-full max-w-5xl"><h1 className="text-3xl font-extrabold sm:text-6xl lg:text-7xl">VÌ MỘT HÀ NỘI <span className="mt-1 block bg-gradient-to-r from-emerald-300 via-lime-300 to-amber-300 bg-clip-text text-transparent">XANH – SẠCH – ĐẸP</span></h1><p className="mx-auto my-8 max-w-3xl text-lg text-emerald-100 sm:text-2xl">Cùng người trẻ Thủ đô hành động vì môi trường và cộng đồng.</p><div className="flex flex-col justify-center gap-4 sm:flex-row"><Link to="/ban-do" className="rounded-xl bg-emerald-600 px-8 py-4 text-lg font-bold">Xem bản đồ hoạt động</Link><Link to={upcoming[0] ? `/dang-ky/${upcoming[0].id}` : "/chien-dich"} className="rounded-xl border border-white/30 bg-white/10 px-8 py-4 text-lg font-bold">Đăng ký tình nguyện</Link></div><div className="mt-14 grid grid-cols-2 gap-3 border-t border-white/20 pt-8 md:grid-cols-4">{[["200+", "Chiến dịch"], ["1.000+", "Tình nguyện viên"], ["20.000", "Lượt tham gia"], ["50+ km", "Sông, mương làm sạch"]].map(([n, l]) => <div key={l} className="rounded-2xl border border-white/20 bg-white/10 p-3"><strong className="block text-2xl text-lime-300 sm:text-4xl">{n}</strong><span className="text-[10px] font-bold uppercase sm:text-xs">{l}</span></div>)}</div></div></section>

    <section className="bg-white py-20"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Về Hà Nội Xanh</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Từ 3 thành viên đến hơn 1.000 tình nguyện viên</h2><p className="mt-5 text-lg leading-relaxed text-gray-600">Được thành lập vào tháng 12/2022, Hà Nội Xanh kết nối người trẻ từ nhiều ngành nghề để cải thiện ô nhiễm, nâng cao trách nhiệm cộng đồng và lan tỏa lối sống xanh.</p><ul className="mt-6 space-y-3">{["Dọn rác tại sông, mương và không gian công cộng.", "Truyền thông, giáo dục môi trường tại các trường đại học.", "Thiện nguyện và triển khai giải pháp phao chắn rác."].map((item) => <li key={item}>✓ {item}</li>)}</ul><Link to="/ve-ha-noi-xanh" className="mt-7 inline-block rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">Về Hà Nội Xanh →</Link></div><img src={heroBg} alt="Hoạt động Hà Nội Xanh" loading="lazy" className="h-[420px] w-full rounded-2xl object-cover shadow-xl" /></div></section>

    <section className="bg-gray-50 py-20"><div className="mx-auto max-w-7xl px-4"><Heading eyebrow="Hoạt động nổi bật" title="Những thay đổi nhìn thấy được" text="Hình ảnh trước và sau các đợt làm sạch tại những điểm nóng." /><div className="grid gap-8 md:grid-cols-3">{BEFORE_AFTER_ITEMS.map((card) => <article key={card.id} className="overflow-hidden rounded-2xl border bg-white shadow-lg"><div className="grid h-52 grid-cols-2 gap-0.5"><div className="relative"><img src={card.beforeImg} alt={`Trước khi dọn ${card.location}`} loading="lazy" className="h-full w-full object-cover" /><b className="absolute left-2 top-2 rounded bg-red-600 px-2 py-1 text-xs text-white">TRƯỚC</b></div><div className="relative"><img src={card.afterImg} alt={`Sau khi dọn ${card.location}`} loading="lazy" className="h-full w-full object-cover" /><b className="absolute right-2 top-2 rounded bg-emerald-600 px-2 py-1 text-xs text-white">SAU</b></div></div><div className="p-6"><small className="font-bold text-emerald-700">{card.date} · {card.trash}</small><h3 className="mt-2 text-lg font-bold">{card.location}</h3><Link to={`/ban-do?location=${card.locationId}`} className="mt-5 inline-block font-bold text-emerald-700">Xem điểm trên bản đồ →</Link></div></article>)}</div><div className="mt-10 text-center"><Link to="/chien-dich" className="rounded-xl bg-emerald-700 px-7 py-3 font-bold text-white">Xem chi tiết các chiến dịch</Link></div></div></section>

    <section className="bg-emerald-950 py-20"><div className="mx-auto max-w-7xl px-4"><Heading light eyebrow="Lịch ra quân" title="Cùng hành động trong chiến dịch tiếp theo" text="Trang chủ hiển thị lịch tóm tắt; trang Chiến dịch có đầy đủ thông tin và trạng thái." /><div className="grid gap-6 md:grid-cols-3">{CAMPAIGN_EVENTS.map((event) => { const ended = eventHasEnded(event); return <article key={event.id} className="flex flex-col justify-between rounded-2xl border border-white/15 bg-white/10 p-6 text-white"><div><span className={`rounded-full px-3 py-1 text-xs font-bold ${ended ? "bg-gray-600" : "bg-emerald-500"}`}>{ended ? "Đã kết thúc" : event.status}</span><h3 className="mt-5 text-xl font-bold">{event.title}</h3><p className="mt-4 text-sm text-emerald-100">{formatVietnameseDate(event.date)}<br />{event.startTime}–{event.endTime}<br />{event.location}</p></div>{ended ? <span className="mt-6 rounded-xl bg-gray-700 py-3 text-center text-sm font-bold">Đã kết thúc</span> : <Link to={`/dang-ky/${event.id}`} className="mt-6 rounded-xl bg-emerald-400 py-3 text-center font-bold text-emerald-950">Đăng ký tham gia</Link>}</article>; })}</div><div className="mt-10 text-center"><Link to="/chien-dich" className="font-bold text-emerald-300 underline">Xem toàn bộ lịch ra quân →</Link></div></div></section>

    <section className="bg-gray-50 py-20"><div className="mx-auto max-w-7xl px-4"><Heading eyebrow="Bản đồ hoạt động" title="Theo dõi các tuyến sông và điểm nóng" text="Chọn bản đồ chi tiết để tìm kiếm, lọc quận và xem từng địa điểm." /><div className="relative min-h-[460px] overflow-hidden rounded-2xl bg-emerald-950 shadow-xl"><img src={mapRefImg} alt="Bản đồ các quận Hà Nội" loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-25" />{CLEANUP_LOCATIONS.map((loc) => <Link key={loc.id} to={`/ban-do?location=${loc.id}`} aria-label={`Xem ${loc.title}`} style={{ top: loc.coords.top, left: loc.coords.left }} className="absolute -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-emerald-600 px-3 py-2 text-xs font-black text-white shadow-lg">{loc.id}</Link>)}<div className="absolute inset-x-4 bottom-4 rounded-2xl bg-white p-5 text-center sm:inset-x-auto sm:left-1/2 sm:w-[420px] sm:-translate-x-1/2"><h3 className="font-black">5 điểm hoạt động mẫu đang được theo dõi</h3><Link to="/ban-do" className="mt-3 inline-block rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">Mở bản đồ chi tiết</Link></div></div></div></section>

    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-4"><Heading eyebrow="Tác động cộng đồng" title="Mỗi đóng góp đều tạo nên thay đổi" text="Đồ bảo hộ, dụng cụ thu gom và chi phí xử lý rác giúp mỗi buổi ra quân an toàn hơn." /><div className="grid gap-6 md:grid-cols-3">{[[100000, "Một bộ đồ bảo hộ và găng tay"], [500000, "Dụng cụ thu gom cho một đội"], [2000000, "Xử lý rác cho một buổi quy mô lớn"]].map(([amount, text]) => <article key={amount} className="rounded-2xl border bg-gray-50 p-7"><h3 className="text-2xl font-black text-emerald-800">{Number(amount).toLocaleString("vi-VN")} VNĐ</h3><p className="mt-3 text-gray-600">{text}</p><Link to={`/ung-ho?amount=${amount}`} className="mt-6 inline-block font-bold text-emerald-700">Xem cách ủng hộ →</Link></article>)}</div><div className="mt-10 text-center"><Link to="/tac-dong" className="rounded-xl bg-emerald-800 px-7 py-3 font-bold text-white">Tìm hiểu tác động cộng đồng</Link></div></div></section>

    <section className="bg-gray-50 py-20"><div className="mx-auto max-w-7xl px-4"><Heading eyebrow="Tin tức" title="Tin tức và câu chuyện" text="Những lát cắt về hành trình bảo vệ môi trường của cộng đồng." /><div className="grid gap-6 md:grid-cols-3">{news.map(([title, date, image]) => <article key={title} className="overflow-hidden rounded-2xl border bg-white"><img src={image} alt="" loading="lazy" className="h-48 w-full object-cover" /><div className="p-6"><small className="font-bold text-emerald-700">{date}</small><h3 className="mt-2 text-lg font-bold">{title}</h3><span className="mt-4 inline-block text-sm font-bold text-gray-400">Nội dung đang cập nhật</span></div></article>)}</div><div className="mt-10 text-center"><Link to="/tin-tuc" className="font-bold text-emerald-700 underline">Đến trang Tin tức →</Link></div></div></section>

    <section className="bg-emerald-100 py-16"><div className="mx-auto max-w-4xl px-4 text-center"><h2 className="text-3xl font-black text-emerald-950">Bạn muốn đồng hành cùng Hà Nội Xanh?</h2><p className="mt-4 text-emerald-900">Gửi lời nhắn, báo một điểm ô nhiễm hoặc tham gia chiến dịch gần nhất.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/lien-he" className="rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">Liên hệ Hà Nội Xanh</Link><Link to="/bao-o-nhiem" className="rounded-xl bg-orange-500 px-6 py-3 font-bold text-white">Báo điểm ô nhiễm</Link></div></div></section>
  </>;
}
