import { useCallback, useEffect, useState, type FormEvent, type ReactNode, type ChangeEvent } from "react"
import { useAuth } from "./AuthContext"
import { tableDelete, tableInsert, tableSelect, tableUpdate, uploadPublicFile } from "../lib/supabase"

type Row = Record<string, unknown> & { id: string }
type Form = { title: string; location: string; start_at: string; end_at: string; capacity: string; status: string; description: string; pollution_status: string; action_plan: string; support_equipment: string; image_url: string }
const empty: Form = { title: "", location: "", start_at: "", end_at: "", capacity: "", status: "upcoming", description: "", pollution_status: "", action_plan: "", support_equipment: "", image_url: "" }
const val = (r: Row, k: string) => String(r[k] ?? "")
const localDate = (v: string) => v ? new Date(v).toISOString().slice(0, 16) : ""

export function ConnectedAdminDashboard({ onLogin }: { onLogin?: () => void }) {
  const [profiles, setProfiles] = useState<Row[]>([])
  const { session, profile, signOut } = useAuth(); const [tab, setTab] = useState("campaigns"); const [campaigns, setCampaigns] = useState<Row[]>([]); const [reports, setReports] = useState<Row[]>([]); const [messages, setMessages] = useState<Row[]>([]); const [registrations, setRegistrations] = useState<Row[]>([]); const [partners, setPartners] = useState<Row[]>([]); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<string | null>(null); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false)
  const load = useCallback(async () => { if (!session) return; try { const [c, r, m, v, p] = await Promise.all([tableSelect<Row>("campaigns", "*", session.access_token, "&order=start_at.desc"), tableSelect<Row>("pollution_reports", "*", session.access_token, "&order=created_at.desc"), tableSelect<Row>("contact_messages", "*", session.access_token, "&order=created_at.desc"), tableSelect<Row>("campaign_registrations", "*,campaigns(title)", session.access_token, "&order=created_at.desc"), tableSelect<Row>("partners", "*", session.access_token, "&order=created_at.desc")]); setCampaigns(c); setReports(r); setMessages(m); setRegistrations(v); setPartners(p) } catch (e) { setError(e instanceof Error ? e.message : "Không tải được dữ liệu") } }, [session])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (!session) return; void tableSelect<Row>("campaign_registrations", "*,profiles(full_name,email,phone)", session.access_token, "&order=created_at.desc").then(items => setRegistrations(items.map(r => { const p = (r.profiles || {}) as Record<string, unknown>; return { ...r, name: p.full_name || r.name || '', email: p.email || r.email || '', phone: p.phone || r.phone || '' } }))).catch(() => undefined) }, [session])
  useEffect(() => { if (!session) return; void tableSelect<Row>("profiles", "id,full_name,email,phone", session.access_token).then(setProfiles).catch(() => undefined) }, [session])
  useEffect(() => { if (!profiles.length) return; const byId = new Map(profiles.map(p => [p.id, p])); setRegistrations(items => items.map(r => { const p = byId.get(String(r.user_id)); return p ? { ...r, name: p.full_name, email: p.email, phone: p.phone } : r })); setReports(items => items.map(r => { const p = byId.get(String(r.user_id)); return p ? { ...r, user_id: `${p.full_name} · ${p.email}${p.phone ? ` · ${p.phone}` : ''}` } : r })) }, [profiles, registrations.length, reports.length])
  useEffect(() => { const heading = document.querySelector('.admin-topbar h1'); const names: Record<string, string> = { overview: 'Tổng quan', campaigns: 'Quản lý chiến dịch', registrations: 'Người đăng ký chiến dịch', people: 'Tình nguyện viên', partners: 'Đối tác', messages: 'Lời nhắn từ website', reports: 'Báo cáo ô nhiễm', posts: 'Tin tức' }; if (heading) heading.textContent = names[tab] || 'Bảng điều khiển'; }, [tab])
  useEffect(() => { const sidebar = document.querySelector('.admin-sidebar'); const nav = sidebar?.querySelector('nav'); if (!sidebar || !nav) return; nav.innerHTML = ''; [["overview", "Tổng quan"], ["campaigns", "Chiến dịch"], ["registrations", "Người đăng ký"], ["people", "Tình nguyện viên"], ["partners", "Đối tác"], ["messages", "Lời nhắn"], ["reports", "Báo cáo ô nhiễm"], ["posts", "Tin tức"]].forEach(([key, label]) => { const b = document.createElement('button'); b.textContent = label; b.className = tab === key ? 'active' : ''; b.onclick = () => setTab(key); nav.appendChild(b) }); sidebar.querySelectorAll('.admin-signout').forEach(x => x.remove()); const link = document.createElement('a'); link.dataset.backHome = 'true'; link.href = '/'; link.textContent = '← Về trang chính'; link.className = 'admin-signout'; sidebar.appendChild(link); }, [tab])
  useEffect(() => { const panels = document.querySelectorAll('.admin-grid-2 > .admin-panel'); if (panels.length < 2) return; (panels[0] as HTMLElement).style.display = tab === 'partners' ? 'none' : ''; (panels[1] as HTMLElement).style.display = tab === 'partners' ? '' : 'none'; }, [tab, registrations.length, partners.length])
  useEffect(() => { if (!["overview", "registrations", "posts"].includes(tab)) return; const root = document.querySelector('.admin-content'); if (!root) return; let box = root.querySelector('[data-extra-panel]') as HTMLElement | null; if (!box) { box = document.createElement('section'); box.dataset.extraPanel = 'true'; box.className = 'admin-panel'; root.appendChild(box) } const data = tab === 'registrations' ? registrations : []; const title = tab === 'overview' ? `Tổng quan: ${campaigns.length} chiến dịch · ${registrations.length} đăng ký · ${messages.length} lời nhắn` : tab === 'registrations' ? `Danh sách người đăng ký (${registrations.length})` : 'Tin tức'; box.innerHTML = `<h2>${title}</h2>` + (tab === 'overview' ? '<p>Chọn một mục ở menu để quản lý dữ liệu chi tiết.</p>' : tab === 'posts' ? '<p>Chức năng quản lý tin tức đang tải dữ liệu.</p>' : `<table><thead><tr><th>Họ tên</th><th>Email</th><th>Số điện thoại</th><th>Ngày đăng ký</th></tr></thead><tbody>${data.map(r => `<tr><td>${String(r.name || '')}</td><td>${String(r.email || '')}</td><td>${String(r.phone || '')}</td><td>${String(r.created_at || '')}</td></tr>`).join('')}</tbody></table>`); return () => { box?.remove() } }, [tab, campaigns, registrations, messages])
  useEffect(() => { const b = document.querySelector('.admin-nav-partner') as HTMLButtonElement | null; if (b) b.onclick = () => { setTab('people'); setTimeout(() => { const p = document.querySelectorAll('.admin-grid-2 > .admin-panel'); if (p[0]) (p[0] as HTMLElement).style.display = 'none'; if (p[1]) (p[1] as HTMLElement).style.display = ''; }, 0) } }, [setTab])
  if (!profile || profile.role !== "admin") return <main className="admin-locked"><div><h1>Đăng nhập quản trị</h1>{onLogin && <button className="auth-primary" onClick={onLogin}>ĐĂNG NHẬP</button>}</div></main>
  const set = (key: keyof Form, value: string) => setForm(x => ({ ...x, [key]: value }))
  async function image(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file || !session) return; setUploading(true); try { set("image_url", await uploadPublicFile(file, session.access_token)) } catch (x) { setError(x instanceof Error ? x.message : "Không tải được ảnh") } finally { setUploading(false) } }
  async function save(e: FormEvent) { e.preventDefault(); if (!session) return; try { const payload = { ...form, start_at: new Date(form.start_at).toISOString(), end_at: form.end_at ? new Date(form.end_at).toISOString() : null, capacity: form.capacity ? Number(form.capacity) : null }; if (editing) await tableUpdate("campaigns", `id=eq.${editing}`, payload, session.access_token); else await tableInsert("campaigns", payload, session.access_token); setForm(empty); setEditing(null); await load() } catch (x) { setError(x instanceof Error ? x.message : "Không lưu được chiến dịch") } }
  async function remove(id: string) { if (!session || !confirm("Xóa chiến dịch này?")) return; await tableDelete("campaigns", `id=eq.${id}`, session.access_token); await load() }
  function edit(r: Row) { setEditing(r.id); setForm({ title: val(r, "title"), location: val(r, "location"), start_at: localDate(val(r, "start_at")), end_at: localDate(val(r, "end_at")), capacity: val(r, "capacity"), status: val(r, "status") || "upcoming", description: val(r, "description"), pollution_status: val(r, "pollution_status"), action_plan: val(r, "action_plan"), support_equipment: val(r, "support_equipment"), image_url: val(r, "image_url") }) }
  return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span>🌱</span><div><strong>HÀ NỘI XANH</strong><small>ADMIN CONSOLE</small></div></div><nav>{[["campaigns", "Chiến dịch"], ["messages", "Lời nhắn"], ["reports", "Báo cáo ô nhiễm"], ["people", "Tình nguyện viên & đối tác"]].map(([k, l]) => <button key={k} className={tab === k ? "active" : ""} onClick={() => setTab(k)}>{l}</button>)}</nav><button className="admin-signout" onClick={() => void signOut()}>Đăng xuất</button></aside><section className="admin-content"><header className="admin-topbar"><div><p className="admin-kicker">BẢNG ĐIỀU KHIỂN</p><h1>{tab === "campaigns" ? "Quản lý chiến dịch" : tab === "messages" ? "Lời nhắn từ website" : tab === "reports" ? "Báo cáo ô nhiễm" : "Tình nguyện viên & đối tác"}</h1></div><div className="admin-user"><span>{profile.full_name || profile.email}</span><small>ADMIN</small></div></header>{error && <div className="admin-error">{error}</div>}{tab === "campaigns" && <CampaignForm form={form} set={set} onImage={image} uploading={uploading} editing={!!editing} onSave={save} onCancel={() => { setEditing(null); setForm(empty) }} rows={campaigns} onEdit={edit} onDelete={remove} />}{tab === "messages" && <Simple title={`Lời nhắn (${messages.length})`} rows={messages} cols={[["name", "Người gửi"], ["email", "Email"], ["message", "Nội dung"], ["created_at", "Ngày gửi"]]} />}{tab === "reports" && <Simple title={`Báo cáo (${reports.length})`} rows={reports} cols={[["user_id", "Tài khoản"], ["location_name", "Địa điểm"], ["description", "Mô tả"], ["status", "Trạng thái"]]} />}{tab === "people" && <div className="admin-grid-2"><Simple title={`Tình nguyện viên (${registrations.length})`} rows={registrations} cols={[["user_id", "Tài khoản"], ["created_at", "Ngày đăng ký"]]} /><Simple title={`Đối tác (${partners.length})`} rows={partners} cols={[["name", "Tên"], ["organization", "Tổ chức"], ["email", "Email"]]} /></div>}</section></main>
}
function CampaignForm({ form, set, onImage, uploading, editing, onSave, onCancel, rows, onEdit, onDelete }: { form: Form; set: (k: keyof Form, v: string) => void; onImage: (e: ChangeEvent<HTMLInputElement>) => void; uploading: boolean; editing: boolean; onSave: (e: FormEvent) => void; onCancel: () => void; rows: Row[]; onEdit: (r: Row) => void; onDelete: (id: string) => void }) { return <div className="admin-page"><section className="admin-panel"><h2>{editing ? "Chỉnh sửa chiến dịch" : "Tạo chiến dịch"}</h2><form onSubmit={onSave}><div className="form-grid"><Field label="Tên chiến dịch" value={form.title} required set={v => set("title", v)} /><Field label="Địa điểm" value={form.location} required set={v => set("location", v)} /><Field label="Bắt đầu" type="datetime-local" value={form.start_at} required set={v => set("start_at", v)} /><Field label="Kết thúc" type="datetime-local" value={form.end_at} set={v => set("end_at", v)} /><Field label="Sức chứa" type="number" value={form.capacity} set={v => set("capacity", v)} /><label>Trạng thái<select value={form.status} onChange={e => set("status", e.target.value)}><option value="upcoming">Sắp diễn ra</option><option value="completed">Đã diễn ra</option></select></label></div><Text label="Tình trạng ô nhiễm tại điểm ra quân" value={form.pollution_status} set={v => set("pollution_status", v)} /><Text label="Kế hoạch & mục tiêu hành động" value={form.action_plan} set={v => set("action_plan", v)} /><Text label="Trang bị hỗ trợ từ Hà Nội Xanh" value={form.support_equipment} set={v => set("support_equipment", v)} /><Text label="Mô tả ngắn" value={form.description} set={v => set("description", v)} required /><label className="wide-field">Ảnh chiến dịch<input type="file" accept="image/*" onChange={onImage} />{uploading && <small>Đang tải ảnh…</small>}{form.image_url && <img src={form.image_url} alt="Xem trước" style={{ maxWidth: 180, marginTop: 8, borderRadius: 8 }} />}</label><button className="admin-primary">{editing ? "LƯU THAY ĐỔI" : "TẠO CHIẾN DỊCH"}</button>{editing && <button type="button" onClick={onCancel}>Hủy</button>}</form></section><List title="Tất cả chiến dịch"><table><thead><tr><th>Tên</th><th>Thời gian</th><th>Trạng thái</th><th /></tr></thead><tbody>{rows.map(r => <tr key={r.id}><td>{String(r.title)}</td><td>{new Date(String(r.start_at)).toLocaleString("vi-VN")}</td><td>{String(r.status)}</td><td><button onClick={() => onEdit(r)}>Sửa</button> <button className="link-danger" onClick={() => onDelete(r.id)}>Xóa</button></td></tr>)}</tbody></table></List></div> }
function Field({ label, value, set, type = "text", required = false }: { label: string; value: string; set: (v: string) => void; type?: string; required?: boolean }) { return <label>{label}<input type={type} value={value} required={required} onChange={e => set(e.target.value)} /></label> }
function Text({ label, value, set, required = false }: { label: string; value: string; set: (v: string) => void; required?: boolean }) { return <label className="wide-field">{label}<textarea value={value} required={required} onChange={e => set(e.target.value)} /></label> }
function List({ title, children }: { title: string; children: ReactNode }) { return <section className="admin-panel"><h2>{title}</h2><div className="admin-table-wrap">{children}</div></section> }
function Simple({ title, rows, cols }: { title: string; rows: Row[]; cols: string[][] }) { const volunteer = title.startsWith('Tình nguyện viên'); const actual = volunteer ? [["name", "Họ tên"], ["email", "Email"], ["phone", "Số điện thoại"], ["created_at", "Ngày đăng ký"]] : cols; return <List title={title}><table><thead><tr>{actual.map(c => <th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map(r => <tr key={r.id}>{actual.map(c => <td key={c[0]}>{String(r[c[0]] ?? "")}</td>)}</tr>)}</tbody></table></List> }
